### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by rafic20** [anushbmx/Change-Page-Background-on-Scroll#1]
Hi, I get this error when I try to access the demo link: 
This webpage is not available

ERR_NAME_NOT_RESOLVED
Hide details
The server at demo.techstream.org can't be found, because the DNS lookup failed. DNS is the network service that translates a website's name to its Internet address. This error is most often caused by having no connection to the Internet or a misconfigured network. It can also be caused by an unresponsive DNS server or a firewall preventing Google Chrome from accessing the network.

**Comment by anushbmx** [comment]
@rafic20 sorry I had some issue with domain :) all is well now.
